version: '3'

services:

  app1:
    image: weizzmann/m31_app
    container_name: app1
    ports:
      - "8001:8001"
    environment:
      APP_PORT: ":8001"

  app2:
    image: weizzmann/m31_app
    container_name: app2
    ports:
      - "8002:8002"
    environment:
      APP_PORT: ":8002"

  nginx:
    build: nginx
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2

