### GetUserByID
GET http://localhost:80/users/61bfae801fb383d90fe56fc1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### GetUsers
GET http://localhost/users
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### CreateUser
POST http://localhost:1234/users
Content-Type: application/json

{
  "name": "plex",
  "age":88
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### UpdateUser
PUT http://localhost:1234/users/61bfae8f1fb383d90fe56fc3
Content-Type: application/json

{
  "age": 111
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### DeleteUser
DELETE http://localhost:1234/users/61bfae7b1fb383d90fe56fc0
Content-Type: application/json


> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### MakeFriends
POST http://localhost:1234/users/make_friends
Content-Type: application/json

{
  "source_id": "61bfae7b1fb383d90fe56fc0",
  "target_id": "61bfae9a1fb383d90fe56fc5"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### GetUserFriends
GET http://localhost:1234/users/61bfae7b1fb383d90fe56fc0/friends
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}